version: '3'
services:
  api:
    build: .
    command: 'yarn start:dev'
    container_name: 'auth-backend-dev'
    expose:
      - '8080:8080'
    ports:
      - '8080:8080'
    volumes:
      - "./:/app"
    environment:
      - PORT=8080

